/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nicolaualfredo.contact.view;

import com.nicolaualfredo.contact.controller.AdminController;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolaualfredo
 */
public class AdminView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminView.class.getName());

    /**
     * Creates new form ContactApp
     */
    public AdminView() {
        initComponents();
        loadAdmins();
    }

    private void loadAdmins() {
        AdminController adminController = new AdminController();
        DefaultTableModel model = (DefaultTableModel) tableAdmins.getModel();
        model.setRowCount(0);

        List<com.nicolaualfredo.contact.model.Admin> admins = adminController.getAllAdmins();

        for (com.nicolaualfredo.contact.model.Admin admin : admins) {
            model.addRow(new Object[]{
                admin.getIdAdmin(),
                admin.getUsernameAdmin(),
                admin.getFullName(),
                admin.getEmail()
            });
        }
    }
    
    private void loadByName() {
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHeader = new javax.swing.JPanel();
        subPanelMenu = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        lblContact = new javax.swing.JLabel();
        lblAboutUS = new javax.swing.JLabel();
        PanelForm = new javax.swing.JPanel();
        subPanelHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblAdministraction = new javax.swing.JLabel();
        subPanelForm = new javax.swing.JPanel();
        PanelId = new javax.swing.JPanel();
        lblEmail1 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        PanelUsername = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        PanelPassword = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        PanelFullName = new javax.swing.JPanel();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        PanelEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        subPanelButtons = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        subPanelMessage = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        PanelTable = new javax.swing.JPanel();
        sPTableAdmins = new javax.swing.JScrollPane();
        tableAdmins = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        PanelHeader.setPreferredSize(new java.awt.Dimension(800, 50));

        subPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        subPanelMenu.setPreferredSize(new java.awt.Dimension(200, 50));

        lblAdmin.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(53, 123, 244));
        lblAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin_menu.png"))); // NOI18N
        lblAdmin.setText("ADMIN");
        lblAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Separator.setBackground(new java.awt.Color(53, 123, 244));
        Separator.setForeground(new java.awt.Color(53, 123, 244));
        Separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblContact.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblContact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contact_menu.png"))); // NOI18N
        lblContact.setText("CONTACT");
        lblContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblAboutUS.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblAboutUS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAboutUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about.png"))); // NOI18N
        lblAboutUS.setText("ABOUT US");
        lblAboutUS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout subPanelMenuLayout = new javax.swing.GroupLayout(subPanelMenu);
        subPanelMenu.setLayout(subPanelMenuLayout);
        subPanelMenuLayout.setHorizontalGroup(
            subPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContact, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAboutUS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        subPanelMenuLayout.setVerticalGroup(
            subPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(Separator, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAboutUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addComponent(subPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelHeader, java.awt.BorderLayout.NORTH);

        PanelForm.setBackground(new java.awt.Color(53, 123, 244));
        PanelForm.setPreferredSize(new java.awt.Dimension(350, 450));

        subPanelHeader.setBackground(new java.awt.Color(53, 123, 244));
        subPanelHeader.setPreferredSize(new java.awt.Dimension(300, 65));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        subPanelHeader.add(lblLogo);

        lblAdministraction.setBackground(new java.awt.Color(255, 255, 255));
        lblAdministraction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdministraction.setForeground(new java.awt.Color(255, 255, 255));
        lblAdministraction.setText("Administration");
        subPanelHeader.add(lblAdministraction);

        PanelForm.add(subPanelHeader);

        subPanelForm.setBackground(new java.awt.Color(53, 123, 244));
        subPanelForm.setPreferredSize(new java.awt.Dimension(300, 275));

        PanelId.setBackground(new java.awt.Color(53, 123, 244));
        PanelId.setPreferredSize(new java.awt.Dimension(295, 48));
        PanelId.setLayout(new java.awt.BorderLayout());

        lblEmail1.setBackground(new java.awt.Color(53, 123, 244));
        lblEmail1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail1.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail1.setText("ID");
        PanelId.add(lblEmail1, java.awt.BorderLayout.PAGE_START);

        txtEmail1.setEditable(false);
        txtEmail1.setEnabled(false);
        PanelId.add(txtEmail1, java.awt.BorderLayout.CENTER);

        subPanelForm.add(PanelId);

        PanelUsername.setBackground(new java.awt.Color(53, 123, 244));
        PanelUsername.setPreferredSize(new java.awt.Dimension(295, 48));
        PanelUsername.setLayout(new java.awt.BorderLayout());

        lblUsername.setBackground(new java.awt.Color(53, 123, 244));
        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        PanelUsername.add(lblUsername, java.awt.BorderLayout.PAGE_START);
        PanelUsername.add(txtUsername, java.awt.BorderLayout.CENTER);

        subPanelForm.add(PanelUsername);

        PanelPassword.setBackground(new java.awt.Color(53, 123, 244));
        PanelPassword.setPreferredSize(new java.awt.Dimension(295, 48));
        PanelPassword.setLayout(new java.awt.BorderLayout());

        lblPassword.setBackground(new java.awt.Color(53, 123, 244));
        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        PanelPassword.add(lblPassword, java.awt.BorderLayout.PAGE_START);
        PanelPassword.add(txtPassword, java.awt.BorderLayout.CENTER);

        subPanelForm.add(PanelPassword);

        PanelFullName.setBackground(new java.awt.Color(53, 123, 244));
        PanelFullName.setPreferredSize(new java.awt.Dimension(295, 48));
        PanelFullName.setLayout(new java.awt.BorderLayout());

        lblFullName.setBackground(new java.awt.Color(53, 123, 244));
        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(255, 255, 255));
        lblFullName.setText("Full Name");
        PanelFullName.add(lblFullName, java.awt.BorderLayout.PAGE_START);
        PanelFullName.add(txtFullName, java.awt.BorderLayout.CENTER);

        subPanelForm.add(PanelFullName);

        PanelEmail.setBackground(new java.awt.Color(53, 123, 244));
        PanelEmail.setPreferredSize(new java.awt.Dimension(295, 48));
        PanelEmail.setLayout(new java.awt.BorderLayout());

        lblEmail.setBackground(new java.awt.Color(53, 123, 244));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        PanelEmail.add(lblEmail, java.awt.BorderLayout.PAGE_START);
        PanelEmail.add(txtEmail, java.awt.BorderLayout.CENTER);

        subPanelForm.add(PanelEmail);

        PanelForm.add(subPanelForm);

        subPanelButtons.setBackground(new java.awt.Color(53, 123, 244));
        subPanelButtons.setPreferredSize(new java.awt.Dimension(350, 50));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout subPanelButtonsLayout = new javax.swing.GroupLayout(subPanelButtons);
        subPanelButtons.setLayout(subPanelButtonsLayout);
        subPanelButtonsLayout.setHorizontalGroup(
            subPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelButtonsLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        subPanelButtonsLayout.setVerticalGroup(
            subPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelForm.add(subPanelButtons);

        subPanelMessage.setBackground(new java.awt.Color(53, 123, 244));
        subPanelMessage.setPreferredSize(new java.awt.Dimension(350, 30));

        lblMessage.setFont(new java.awt.Font("Sitka Text", 0, 13)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Admin created successfully!");

        javax.swing.GroupLayout subPanelMessageLayout = new javax.swing.GroupLayout(subPanelMessage);
        subPanelMessage.setLayout(subPanelMessageLayout);
        subPanelMessageLayout.setHorizontalGroup(
            subPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        subPanelMessageLayout.setVerticalGroup(
            subPanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        PanelForm.add(subPanelMessage);

        getContentPane().add(PanelForm, java.awt.BorderLayout.WEST);

        PanelTable.setBackground(new java.awt.Color(255, 255, 255));
        PanelTable.setPreferredSize(new java.awt.Dimension(450, 450));

        tableAdmins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "USERNAME", "FULL NAME", "EMAIL"
            }
        ));
        sPTableAdmins.setViewportView(tableAdmins);

        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        lblSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout PanelTableLayout = new javax.swing.GroupLayout(PanelTable);
        PanelTable.setLayout(PanelTableLayout);
        PanelTableLayout.setHorizontalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTableLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sPTableAdmins, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelTableLayout.setVerticalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTableLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sPTableAdmins, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(PanelTable, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEmail;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JPanel PanelFullName;
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JPanel PanelId;
    private javax.swing.JPanel PanelPassword;
    private javax.swing.JPanel PanelTable;
    private javax.swing.JPanel PanelUsername;
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAboutUS;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAdministraction;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JScrollPane sPTableAdmins;
    private javax.swing.JPanel subPanelButtons;
    private javax.swing.JPanel subPanelForm;
    private javax.swing.JPanel subPanelHeader;
    private javax.swing.JPanel subPanelMenu;
    private javax.swing.JPanel subPanelMessage;
    private javax.swing.JTable tableAdmins;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
