/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.nicolaualfredo.contact.view;

import com.nicolaualfredo.contact.model.Contact;
import java.awt.Frame;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Nicolau Alfredo
 */
public class ContactDetailsView extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContactDetailsView.class.getName());

    /**
     * Creates new form NewJDialog
     */
    private Contact contact;

    public ContactDetailsView(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setContact(Contact contact) {
        this.contact = contact;
        loadData();
    }

    private void showGreetingMessage() {
        int hour = java.time.LocalTime.now().getHour();

        String message;
        if (hour >= 0 && hour < 6) {
            message = "Good early morning!";
        } else if (hour >= 6 && hour < 12) {
            message = "Good morning!";
        } else if (hour >= 12 && hour < 18) {
            message = "Good afternoon!";
        } else {
            message = "Good evening!";
        }

        txtMessage.setText(message);
    }

    private void loadData() {

        if (contact == null) {
            txtMessage.setText("No contact data found.");
            return;
        }

        if (contact.getPhotoPath() != null && !contact.getPhotoPath().isEmpty()) {
            ImageIcon icon = new ImageIcon(contact.getPhotoPath());
            Image scaled = icon.getImage().getScaledInstance(128, 128, Image.SCALE_SMOOTH);
            lblPhoto.setIcon(new ImageIcon(scaled));
        } else {
            txtMessage.setText("No photo found.");
        }

        txtId.setText(String.valueOf(contact.getIdContact()));
        txtName.setText(contact.getNameContact());
        txtPhone.setText(contact.getPhoneContact());
        txtEmail.setText(contact.getEmailContact());
        showGreetingMessage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHeader = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        txtMessage = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        subPanelPhoto = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        PanelDetails = new javax.swing.JPanel();
        subPanelForm = new javax.swing.JPanel();
        panelName = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        splblName = new javax.swing.JSeparator();
        panelPhone = new javax.swing.JPanel();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JLabel();
        splblPhone = new javax.swing.JSeparator();
        panelEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        splblEmail = new javax.swing.JSeparator();
        subPanelSocials = new javax.swing.JPanel();
        lblFacebook = new javax.swing.JLabel();
        lblInstagram = new javax.swing.JLabel();
        lblGitHub = new javax.swing.JLabel();
        lblWhatsApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contact Details");
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        PanelHeader.setBackground(new java.awt.Color(53, 123, 244));
        PanelHeader.setPreferredSize(new java.awt.Dimension(600, 50));

        lblId.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Number:");

        txtId.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setText("The ID will stay here");

        txtMessage.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        txtMessage.setForeground(new java.awt.Color(255, 255, 255));
        txtMessage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtMessage.setText("Message");

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(PanelHeader, java.awt.BorderLayout.PAGE_START);

        PanelInfo.setPreferredSize(new java.awt.Dimension(600, 350));
        PanelInfo.setLayout(new java.awt.BorderLayout());

        subPanelPhoto.setBackground(new java.awt.Color(255, 255, 255));
        subPanelPhoto.setPreferredSize(new java.awt.Dimension(250, 0));

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/photo.png"))); // NOI18N

        javax.swing.GroupLayout subPanelPhotoLayout = new javax.swing.GroupLayout(subPanelPhoto);
        subPanelPhoto.setLayout(subPanelPhotoLayout);
        subPanelPhotoLayout.setHorizontalGroup(
            subPanelPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelPhotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        subPanelPhotoLayout.setVerticalGroup(
            subPanelPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelPhotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelInfo.add(subPanelPhoto, java.awt.BorderLayout.WEST);

        PanelDetails.setBackground(new java.awt.Color(255, 255, 255));
        PanelDetails.setPreferredSize(new java.awt.Dimension(350, 0));

        subPanelForm.setBackground(new java.awt.Color(255, 255, 255));
        subPanelForm.setPreferredSize(new java.awt.Dimension(350, 180));

        panelName.setBackground(new java.awt.Color(255, 255, 255));
        panelName.setPreferredSize(new java.awt.Dimension(300, 50));
        panelName.setLayout(new java.awt.BorderLayout());

        lblName.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        lblName.setText("Name");
        panelName.add(lblName, java.awt.BorderLayout.PAGE_START);

        txtName.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(53, 123, 244));
        txtName.setText("The name will stay here");
        panelName.add(txtName, java.awt.BorderLayout.CENTER);

        splblName.setBackground(new java.awt.Color(0, 0, 0));
        splblName.setForeground(new java.awt.Color(0, 0, 0));
        panelName.add(splblName, java.awt.BorderLayout.PAGE_END);

        subPanelForm.add(panelName);

        panelPhone.setBackground(new java.awt.Color(255, 255, 255));
        panelPhone.setPreferredSize(new java.awt.Dimension(300, 50));
        panelPhone.setLayout(new java.awt.BorderLayout());

        lblPhone.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        lblPhone.setText("Phone");
        panelPhone.add(lblPhone, java.awt.BorderLayout.PAGE_START);

        txtPhone.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(53, 123, 244));
        txtPhone.setText("The phone will stay here");
        panelPhone.add(txtPhone, java.awt.BorderLayout.CENTER);

        splblPhone.setBackground(new java.awt.Color(0, 0, 0));
        splblPhone.setForeground(new java.awt.Color(0, 0, 0));
        panelPhone.add(splblPhone, java.awt.BorderLayout.PAGE_END);

        subPanelForm.add(panelPhone);

        panelEmail.setBackground(new java.awt.Color(255, 255, 255));
        panelEmail.setPreferredSize(new java.awt.Dimension(300, 50));
        panelEmail.setLayout(new java.awt.BorderLayout());

        lblEmail.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        lblEmail.setText("Email");
        panelEmail.add(lblEmail, java.awt.BorderLayout.PAGE_START);

        txtEmail.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(53, 123, 244));
        txtEmail.setText("The email will stay here");
        panelEmail.add(txtEmail, java.awt.BorderLayout.CENTER);

        splblEmail.setBackground(new java.awt.Color(0, 0, 0));
        splblEmail.setForeground(new java.awt.Color(0, 0, 0));
        panelEmail.add(splblEmail, java.awt.BorderLayout.PAGE_END);

        subPanelForm.add(panelEmail);

        PanelDetails.add(subPanelForm);

        subPanelSocials.setBackground(new java.awt.Color(255, 255, 255));
        subPanelSocials.setPreferredSize(new java.awt.Dimension(350, 90));

        lblFacebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacebook.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nicolau Alfredo\\Documents\\NetBeansProjects\\contactApp\\src\\main\\resources\\icons\\facebook.png")); // NOI18N
        lblFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFacebook.setPreferredSize(new java.awt.Dimension(80, 80));
        subPanelSocials.add(lblFacebook);

        lblInstagram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/instagram.png"))); // NOI18N
        lblInstagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInstagram.setPreferredSize(new java.awt.Dimension(80, 80));
        subPanelSocials.add(lblInstagram);

        lblGitHub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGitHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/github.png"))); // NOI18N
        lblGitHub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGitHub.setPreferredSize(new java.awt.Dimension(80, 80));
        subPanelSocials.add(lblGitHub);

        lblWhatsApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWhatsApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whatsapp.png"))); // NOI18N
        lblWhatsApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblWhatsApp.setPreferredSize(new java.awt.Dimension(80, 80));
        subPanelSocials.add(lblWhatsApp);

        PanelDetails.add(subPanelSocials);

        PanelInfo.add(PanelDetails, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelInfo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ContactDetailsView dialog1 = new ContactDetailsView(new javax.swing.JFrame(), true);
            dialog1.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog1.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDetails;
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFacebook;
    private javax.swing.JLabel lblGitHub;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblInstagram;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblWhatsApp;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelName;
    private javax.swing.JPanel panelPhone;
    private javax.swing.JSeparator splblEmail;
    private javax.swing.JSeparator splblName;
    private javax.swing.JSeparator splblPhone;
    private javax.swing.JPanel subPanelForm;
    private javax.swing.JPanel subPanelPhoto;
    private javax.swing.JPanel subPanelSocials;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtMessage;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPhone;
    // End of variables declaration//GEN-END:variables
}
