/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nicolaualfredo.contact.view;

/**
 *
 * @author Nicolau Alfredo
 */
public class PasswordReset extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PasswordReset.class.getName());

    /**
     * Creates new form PasswordReset
     */
    public PasswordReset() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        PanelPasswordReset = new javax.swing.JPanel();
        subPanelHeader = new javax.swing.JPanel();
        lblPasswordReset = new javax.swing.JLabel();
        lblText1 = new javax.swing.JLabel();
        lblText2 = new javax.swing.JLabel();
        subPanelForm = new javax.swing.JPanel();
        PanelUsername = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PanelMasterKey = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        PanelLogin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        subPanelSignUp = new javax.swing.JPanel();
        lblText3 = new javax.swing.JLabel();
        lblSignUp = new javax.swing.JLabel();
        subPanelResetPassword = new javax.swing.JPanel();
        btnResetPassword = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Reset");
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        PanelLogo.setBackground(new java.awt.Color(53, 123, 244));
        PanelLogo.setPreferredSize(new java.awt.Dimension(200, 500));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password.png"))); // NOI18N

        javax.swing.GroupLayout PanelLogoLayout = new javax.swing.GroupLayout(PanelLogo);
        PanelLogo.setLayout(PanelLogoLayout);
        PanelLogoLayout.setHorizontalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelLogoLayout.setVerticalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(PanelLogo, java.awt.BorderLayout.WEST);

        PanelPasswordReset.setBackground(new java.awt.Color(255, 255, 255));
        PanelPasswordReset.setPreferredSize(new java.awt.Dimension(400, 500));

        subPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        subPanelHeader.setPreferredSize(new java.awt.Dimension(400, 170));

        lblPasswordReset.setBackground(new java.awt.Color(255, 255, 255));
        lblPasswordReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPasswordReset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPasswordReset.setText("Password Reset");
        lblPasswordReset.setPreferredSize(new java.awt.Dimension(147, 50));

        lblText1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblText1.setText("Provide the username and the reset master key");
        lblText1.setPreferredSize(new java.awt.Dimension(275, 50));

        lblText2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblText2.setText("to recover your password.");

        javax.swing.GroupLayout subPanelHeaderLayout = new javax.swing.GroupLayout(subPanelHeader);
        subPanelHeader.setLayout(subPanelHeaderLayout);
        subPanelHeaderLayout.setHorizontalGroup(
            subPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(subPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordReset, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText2))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        subPanelHeaderLayout.setVerticalGroup(
            subPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelHeaderLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblPasswordReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblText1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblText2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelPasswordReset.add(subPanelHeader);

        subPanelForm.setBackground(new java.awt.Color(255, 255, 255));
        subPanelForm.setPreferredSize(new java.awt.Dimension(400, 140));

        PanelUsername.setBackground(new java.awt.Color(255, 255, 255));
        PanelUsername.setPreferredSize(new java.awt.Dimension(350, 50));
        PanelUsername.setLayout(new java.awt.BorderLayout(4, 4));
        PanelUsername.add(jTextField1, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Username");
        PanelUsername.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        subPanelForm.add(PanelUsername);

        PanelMasterKey.setBackground(new java.awt.Color(255, 255, 255));
        PanelMasterKey.setPreferredSize(new java.awt.Dimension(350, 50));
        PanelMasterKey.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel3.setText("Reset Master Key");
        PanelMasterKey.add(jLabel3, java.awt.BorderLayout.PAGE_START);
        PanelMasterKey.add(jPasswordField1, java.awt.BorderLayout.CENTER);

        subPanelForm.add(PanelMasterKey);

        PanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        PanelLogin.setPreferredSize(new java.awt.Dimension(350, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 123, 244));
        jLabel4.setText("Log In");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setPreferredSize(new java.awt.Dimension(34, 10));

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        subPanelForm.add(PanelLogin);

        PanelPasswordReset.add(subPanelForm);

        subPanelSignUp.setBackground(new java.awt.Color(255, 255, 255));
        subPanelSignUp.setPreferredSize(new java.awt.Dimension(400, 30));

        lblText3.setBackground(new java.awt.Color(84, 86, 255));
        lblText3.setText("Don't have an account yet?");
        subPanelSignUp.add(lblText3);

        lblSignUp.setBackground(new java.awt.Color(255, 255, 255));
        lblSignUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(53, 123, 244));
        lblSignUp.setText("Sign up.");
        lblSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subPanelSignUp.add(lblSignUp);

        PanelPasswordReset.add(subPanelSignUp);

        subPanelResetPassword.setBackground(new java.awt.Color(255, 255, 255));
        subPanelResetPassword.setPreferredSize(new java.awt.Dimension(400, 50));

        btnResetPassword.setBackground(new java.awt.Color(53, 123, 244));
        btnResetPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPassword.setText("Reset Password");
        btnResetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetPassword.setPreferredSize(new java.awt.Dimension(250, 30));

        javax.swing.GroupLayout subPanelResetPasswordLayout = new javax.swing.GroupLayout(subPanelResetPassword);
        subPanelResetPassword.setLayout(subPanelResetPasswordLayout);
        subPanelResetPasswordLayout.setHorizontalGroup(
            subPanelResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelResetPasswordLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        subPanelResetPasswordLayout.setVerticalGroup(
            subPanelResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelResetPasswordLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelPasswordReset.add(subPanelResetPassword);

        lblMessage.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(53, 123, 244));
        lblMessage.setText("Password updated successfully.");
        PanelPasswordReset.add(lblMessage);

        getContentPane().add(PanelPasswordReset, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PasswordReset().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JPanel PanelMasterKey;
    private javax.swing.JPanel PanelPasswordReset;
    private javax.swing.JPanel PanelUsername;
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPasswordReset;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblText1;
    private javax.swing.JLabel lblText2;
    private javax.swing.JLabel lblText3;
    private javax.swing.JPanel subPanelForm;
    private javax.swing.JPanel subPanelHeader;
    private javax.swing.JPanel subPanelResetPassword;
    private javax.swing.JPanel subPanelSignUp;
    // End of variables declaration//GEN-END:variables
}
