/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nicolaualfredo.contact.view;

/**
 *
 * @author Nicolau Alfredo
 */
public class Signup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signup.class.getName());

    /**
     * Creates new form f
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        PanelJoinUs = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        PanelSignUp = new javax.swing.JPanel();
        subPanelSignUp = new javax.swing.JPanel();
        lblSignUp = new javax.swing.JLabel();
        subPanelForm = new javax.swing.JPanel();
        panelUsername = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        panelFullName = new javax.swing.JPanel();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        panelEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        subPanelButton = new javax.swing.JPanel();
        btnSignUp = new javax.swing.JButton();
        subPanelSocial = new javax.swing.JPanel();
        lblOr = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblFacebook = new javax.swing.JLabel();
        lblGoogle = new javax.swing.JLabel();
        lblGitHub = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelJoinUs.setBackground(new java.awt.Color(53, 123, 244));
        PanelJoinUs.setPreferredSize(new java.awt.Dimension(400, 500));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/upload.png"))); // NOI18N

        javax.swing.GroupLayout PanelJoinUsLayout = new javax.swing.GroupLayout(PanelJoinUs);
        PanelJoinUs.setLayout(PanelJoinUsLayout);
        PanelJoinUsLayout.setHorizontalGroup(
            PanelJoinUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJoinUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelJoinUsLayout.setVerticalGroup(
            PanelJoinUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJoinUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(PanelJoinUs, java.awt.BorderLayout.WEST);

        PanelSignUp.setBackground(new java.awt.Color(255, 255, 255));
        PanelSignUp.setPreferredSize(new java.awt.Dimension(400, 500));

        subPanelSignUp.setBackground(new java.awt.Color(255, 255, 255));
        subPanelSignUp.setPreferredSize(new java.awt.Dimension(400, 40));

        lblSignUp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignUp.setText("SIGN UP");

        javax.swing.GroupLayout subPanelSignUpLayout = new javax.swing.GroupLayout(subPanelSignUp);
        subPanelSignUp.setLayout(subPanelSignUpLayout);
        subPanelSignUpLayout.setHorizontalGroup(
            subPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        subPanelSignUpLayout.setVerticalGroup(
            subPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelSignUp.add(subPanelSignUp);

        subPanelForm.setBackground(new java.awt.Color(255, 255, 255));
        subPanelForm.setPreferredSize(new java.awt.Dimension(400, 230));

        panelUsername.setBackground(new java.awt.Color(255, 255, 255));
        panelUsername.setPreferredSize(new java.awt.Dimension(380, 50));
        panelUsername.setLayout(new java.awt.BorderLayout());

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setText("Username");
        lblUsername.setMaximumSize(new java.awt.Dimension(30, 20));
        lblUsername.setMinimumSize(new java.awt.Dimension(30, 20));
        lblUsername.setPreferredSize(new java.awt.Dimension(30, 20));
        panelUsername.add(lblUsername, java.awt.BorderLayout.PAGE_START);
        panelUsername.add(txtUsername, java.awt.BorderLayout.CENTER);

        subPanelForm.add(panelUsername);

        panelPassword.setBackground(new java.awt.Color(255, 255, 255));
        panelPassword.setPreferredSize(new java.awt.Dimension(380, 50));
        panelPassword.setLayout(new java.awt.BorderLayout());

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setText("Password");
        lblPassword.setMaximumSize(new java.awt.Dimension(30, 20));
        lblPassword.setMinimumSize(new java.awt.Dimension(30, 20));
        lblPassword.setPreferredSize(new java.awt.Dimension(30, 20));
        panelPassword.add(lblPassword, java.awt.BorderLayout.PAGE_START);
        panelPassword.add(txtPassword, java.awt.BorderLayout.CENTER);

        subPanelForm.add(panelPassword);

        panelFullName.setBackground(new java.awt.Color(255, 255, 255));
        panelFullName.setPreferredSize(new java.awt.Dimension(380, 50));
        panelFullName.setLayout(new java.awt.BorderLayout());

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFullName.setText("Full Name");
        lblFullName.setMaximumSize(new java.awt.Dimension(30, 20));
        lblFullName.setMinimumSize(new java.awt.Dimension(30, 20));
        lblFullName.setPreferredSize(new java.awt.Dimension(30, 20));
        panelFullName.add(lblFullName, java.awt.BorderLayout.PAGE_START);

        txtFullName.setPreferredSize(new java.awt.Dimension(64, 22));
        txtFullName.setSelectionEnd(0);
        txtFullName.setSelectionStart(0);
        panelFullName.add(txtFullName, java.awt.BorderLayout.CENTER);

        subPanelForm.add(panelFullName);

        panelEmail.setBackground(new java.awt.Color(255, 255, 255));
        panelEmail.setPreferredSize(new java.awt.Dimension(380, 50));
        panelEmail.setLayout(new java.awt.BorderLayout());

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.setMaximumSize(new java.awt.Dimension(30, 20));
        lblEmail.setMinimumSize(new java.awt.Dimension(30, 20));
        lblEmail.setPreferredSize(new java.awt.Dimension(30, 20));
        panelEmail.add(lblEmail, java.awt.BorderLayout.PAGE_START);
        panelEmail.add(txtEmail, java.awt.BorderLayout.CENTER);

        subPanelForm.add(panelEmail);

        PanelSignUp.add(subPanelForm);

        subPanelButton.setBackground(new java.awt.Color(255, 255, 255));
        subPanelButton.setPreferredSize(new java.awt.Dimension(400, 60));

        btnSignUp.setBackground(new java.awt.Color(53, 123, 244));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("SIGN UP");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout subPanelButtonLayout = new javax.swing.GroupLayout(subPanelButton);
        subPanelButton.setLayout(subPanelButtonLayout);
        subPanelButtonLayout.setHorizontalGroup(
            subPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        subPanelButtonLayout.setVerticalGroup(
            subPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelSignUp.add(subPanelButton);

        subPanelSocial.setBackground(new java.awt.Color(255, 255, 255));
        subPanelSocial.setPreferredSize(new java.awt.Dimension(400, 200));

        lblOr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblOr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOr.setText("or signup with");
        lblOr.setPreferredSize(new java.awt.Dimension(400, 25));
        subPanelSocial.add(lblOr);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 100));

        lblFacebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacebook.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nicolau Alfredo\\Documents\\NetBeansProjects\\contactApp\\src\\main\\resources\\icons\\facebook.png")); // NOI18N
        lblFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFacebook.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel2.add(lblFacebook);

        lblGoogle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/google.png"))); // NOI18N
        lblGoogle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGoogle.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel2.add(lblGoogle);

        lblGitHub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGitHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/github.png"))); // NOI18N
        lblGitHub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGitHub.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel2.add(lblGitHub);

        subPanelSocial.add(jPanel2);

        PanelSignUp.add(subPanelSocial);

        getContentPane().add(PanelSignUp, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelJoinUs;
    private javax.swing.JPanel PanelSignUp;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFacebook;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGitHub;
    private javax.swing.JLabel lblGoogle;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblOr;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelFullName;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelUsername;
    private javax.swing.JPanel subPanelButton;
    private javax.swing.JPanel subPanelForm;
    private javax.swing.JPanel subPanelSignUp;
    private javax.swing.JPanel subPanelSocial;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
