/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nicolaualfredo.contact.view;

import com.nicolaualfredo.contact.controller.AdminController;
import com.nicolaualfredo.contact.model.Admin;
import com.nicolaualfredo.contact.util.PasswordUtil;
import java.sql.Timestamp;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author Nicolau Alfredo
 */
public class SignupView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignupView.class.getName());

    /**
     * Creates new form f
     */
    public SignupView() {
        initComponents();
    }

    public void showTemporaryMessage(JLabel label, String message, int durationMillis) {
        label.setText(message);

        Timer timer = new Timer(durationMillis, e -> label.setText(""));
        timer.setRepeats(false);
        timer.start();
    }

    private boolean validateFields() {
        if (txtUsername.getText().trim().isEmpty() || txtPassword.getText().trim().isEmpty() || txtFullName.getText().trim().isEmpty() || txtEmail.getText().trim().isEmpty()) {
            showTemporaryMessage(lblMessage, "Please fill in all required fields.", 5000);
            return false;
        }
        return true;
    }

    private void clearFields() {
        txtUsername.setText("");
        txtPassword.setText("");
        txtFullName.setText("");
        txtEmail.setText("");
    }

    private void signUp() {
        if (!validateFields()) {
            return;
        }

        String username = txtUsername.getText().trim();
        AdminController controller = new AdminController();

        if (controller.usernameExists(username)) {
            showTemporaryMessage(lblMessage, "Username already exists. Please choose another one.", 5000);
            return;
        }

        Admin admin = new Admin();
        admin.setUsernameAdmin(username);
        admin.setPassword_has(PasswordUtil.hash(txtPassword.getText().trim()));
        admin.setFullName(txtFullName.getText().trim());
        admin.setEmail(txtEmail.getText().trim());
        admin.setCreated_at(new Timestamp(System.currentTimeMillis()));

        if (controller.createAdmin(admin)) {
            showTemporaryMessage(lblMessage, "Admin created successfully.", 5000);
            clearFields();
        } else {
            showTemporaryMessage(lblMessage, "Failed to create admin. Please try again.", 5000);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        PanelJoinUs = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        PanelSignUp = new javax.swing.JPanel();
        subPanelSignUp = new javax.swing.JPanel();
        lblSignUp = new javax.swing.JLabel();
        subPanelForm = new javax.swing.JPanel();
        panelUsername = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        panelFullName = new javax.swing.JPanel();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        panelEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        subPanelButton = new javax.swing.JPanel();
        btnSignUp = new javax.swing.JButton();
        subPanelLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        subPanelSocial = new javax.swing.JPanel();
        lblOr = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblFacebook = new javax.swing.JLabel();
        lblGoogle = new javax.swing.JLabel();
        lblGitHub = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelJoinUs.setBackground(new java.awt.Color(53, 123, 244));
        PanelJoinUs.setPreferredSize(new java.awt.Dimension(400, 500));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/upload.png"))); // NOI18N

        lblMessage.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelJoinUsLayout = new javax.swing.GroupLayout(PanelJoinUs);
        PanelJoinUs.setLayout(PanelJoinUsLayout);
        PanelJoinUsLayout.setHorizontalGroup(
            PanelJoinUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJoinUsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelJoinUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelJoinUsLayout.setVerticalGroup(
            PanelJoinUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJoinUsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PanelJoinUs, java.awt.BorderLayout.WEST);

        PanelSignUp.setBackground(new java.awt.Color(255, 255, 255));
        PanelSignUp.setPreferredSize(new java.awt.Dimension(400, 500));

        subPanelSignUp.setBackground(new java.awt.Color(255, 255, 255));
        subPanelSignUp.setPreferredSize(new java.awt.Dimension(400, 40));

        lblSignUp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignUp.setText("SIGN UP");

        javax.swing.GroupLayout subPanelSignUpLayout = new javax.swing.GroupLayout(subPanelSignUp);
        subPanelSignUp.setLayout(subPanelSignUpLayout);
        subPanelSignUpLayout.setHorizontalGroup(
            subPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        subPanelSignUpLayout.setVerticalGroup(
            subPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelSignUp.add(subPanelSignUp);

        subPanelForm.setBackground(new java.awt.Color(255, 255, 255));
        subPanelForm.setPreferredSize(new java.awt.Dimension(400, 230));

        panelUsername.setBackground(new java.awt.Color(255, 255, 255));
        panelUsername.setPreferredSize(new java.awt.Dimension(380, 50));
        panelUsername.setLayout(new java.awt.BorderLayout());

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsername.setText("Username");
        lblUsername.setMaximumSize(new java.awt.Dimension(30, 20));
        lblUsername.setMinimumSize(new java.awt.Dimension(30, 20));
        lblUsername.setPreferredSize(new java.awt.Dimension(30, 20));
        panelUsername.add(lblUsername, java.awt.BorderLayout.PAGE_START);
        panelUsername.add(txtUsername, java.awt.BorderLayout.CENTER);

        subPanelForm.add(panelUsername);

        panelPassword.setBackground(new java.awt.Color(255, 255, 255));
        panelPassword.setPreferredSize(new java.awt.Dimension(380, 50));
        panelPassword.setLayout(new java.awt.BorderLayout());

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setText("Password");
        lblPassword.setMaximumSize(new java.awt.Dimension(30, 20));
        lblPassword.setMinimumSize(new java.awt.Dimension(30, 20));
        lblPassword.setPreferredSize(new java.awt.Dimension(30, 20));
        panelPassword.add(lblPassword, java.awt.BorderLayout.PAGE_START);
        panelPassword.add(txtPassword, java.awt.BorderLayout.CENTER);

        subPanelForm.add(panelPassword);

        panelFullName.setBackground(new java.awt.Color(255, 255, 255));
        panelFullName.setPreferredSize(new java.awt.Dimension(380, 50));
        panelFullName.setLayout(new java.awt.BorderLayout());

        lblFullName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFullName.setText("Full Name");
        lblFullName.setMaximumSize(new java.awt.Dimension(30, 20));
        lblFullName.setMinimumSize(new java.awt.Dimension(30, 20));
        lblFullName.setPreferredSize(new java.awt.Dimension(30, 20));
        panelFullName.add(lblFullName, java.awt.BorderLayout.PAGE_START);
        panelFullName.add(txtFullName, java.awt.BorderLayout.CENTER);

        subPanelForm.add(panelFullName);

        panelEmail.setBackground(new java.awt.Color(255, 255, 255));
        panelEmail.setPreferredSize(new java.awt.Dimension(380, 50));
        panelEmail.setLayout(new java.awt.BorderLayout());

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.setMaximumSize(new java.awt.Dimension(30, 20));
        lblEmail.setMinimumSize(new java.awt.Dimension(30, 20));
        lblEmail.setPreferredSize(new java.awt.Dimension(30, 20));
        panelEmail.add(lblEmail, java.awt.BorderLayout.PAGE_START);
        panelEmail.add(txtEmail, java.awt.BorderLayout.CENTER);

        subPanelForm.add(panelEmail);

        PanelSignUp.add(subPanelForm);

        subPanelButton.setBackground(new java.awt.Color(255, 255, 255));
        subPanelButton.setPreferredSize(new java.awt.Dimension(400, 50));

        btnSignUp.setBackground(new java.awt.Color(53, 123, 244));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("SIGN UP");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout subPanelButtonLayout = new javax.swing.GroupLayout(subPanelButton);
        subPanelButton.setLayout(subPanelButtonLayout);
        subPanelButtonLayout.setHorizontalGroup(
            subPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        subPanelButtonLayout.setVerticalGroup(
            subPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelSignUp.add(subPanelButton);

        subPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        subPanelLogin.setPreferredSize(new java.awt.Dimension(400, 30));

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(53, 123, 244));
        lblLogin.setText("Log In");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout subPanelLoginLayout = new javax.swing.GroupLayout(subPanelLogin);
        subPanelLogin.setLayout(subPanelLoginLayout);
        subPanelLoginLayout.setHorizontalGroup(
            subPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        subPanelLoginLayout.setVerticalGroup(
            subPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelSignUp.add(subPanelLogin);

        subPanelSocial.setBackground(new java.awt.Color(255, 255, 255));
        subPanelSocial.setPreferredSize(new java.awt.Dimension(400, 180));

        lblOr.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblOr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOr.setText("or signup with");
        lblOr.setPreferredSize(new java.awt.Dimension(400, 22));
        subPanelSocial.add(lblOr);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 80));

        lblFacebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacebook.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nicolau Alfredo\\Documents\\NetBeansProjects\\contactApp\\src\\main\\resources\\icons\\facebook.png")); // NOI18N
        lblFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFacebook.setPreferredSize(new java.awt.Dimension(80, 80));
        lblFacebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFacebookMouseClicked(evt);
            }
        });
        jPanel2.add(lblFacebook);

        lblGoogle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/google.png"))); // NOI18N
        lblGoogle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGoogle.setPreferredSize(new java.awt.Dimension(80, 80));
        lblGoogle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGoogleMouseClicked(evt);
            }
        });
        jPanel2.add(lblGoogle);

        lblGitHub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGitHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/github.png"))); // NOI18N
        lblGitHub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGitHub.setPreferredSize(new java.awt.Dimension(80, 80));
        lblGitHub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGitHubMouseClicked(evt);
            }
        });
        jPanel2.add(lblGitHub);

        subPanelSocial.add(jPanel2);

        PanelSignUp.add(subPanelSocial);

        getContentPane().add(PanelSignUp, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        // TODO add your handling code here:
        signUp();
    }//GEN-LAST:event_btnSignUpMouseClicked

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        // TODO add your handling code here:
        new LoginView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblFacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacebookMouseClicked
        // TODO add your handling code here:
        showTemporaryMessage(lblMessage, "Come soon!!", 5000);
    }//GEN-LAST:event_lblFacebookMouseClicked

    private void lblGoogleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoogleMouseClicked
        // TODO add your handling code here:
        showTemporaryMessage(lblMessage, "Come soon!!", 5000);
    }//GEN-LAST:event_lblGoogleMouseClicked

    private void lblGitHubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGitHubMouseClicked
        // TODO add your handling code here:
        showTemporaryMessage(lblMessage, "Come soon!!", 5000);
    }//GEN-LAST:event_lblGitHubMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignupView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelJoinUs;
    private javax.swing.JPanel PanelSignUp;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFacebook;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGitHub;
    private javax.swing.JLabel lblGoogle;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblOr;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelFullName;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelUsername;
    private javax.swing.JPanel subPanelButton;
    private javax.swing.JPanel subPanelForm;
    private javax.swing.JPanel subPanelLogin;
    private javax.swing.JPanel subPanelSignUp;
    private javax.swing.JPanel subPanelSocial;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
